name: javascript

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: use node.js 22.x
        uses: actions/setup-node@master
        with:
          node-version: 22.x

      - name: install packages
        run: yarn install --immutable --silent

      - name: Test with jest
        run: yarn test
